services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: current-ng-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: current-ng-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data


